# Generated by Django 5.2.7 on 2025-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='captured_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='channel_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='duration_seconds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='original_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='parse_status',
            field=models.CharField(default='pending'),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='recovered_uri',
            field=models.CharField(default='pending'),
        ),
    ]
