# Generated by Django 5.2.7 on 2025-11-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mcaplog_captured_at_mcaplog_channel_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='recovery_status',
            field=models.CharField(default='pending'),
        ),
    ]
