# Generated by Django 5.2.7 on 2025-11-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mcaplog_lap_path_alter_mcaplog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcaplog',
            name='location',
        ),
    ]
