# Generated by Django 5.2.7 on 2025-11-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_mcaplog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
