# Generated by Django 5.2.7 on 2025-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mcaplog_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='parse_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for parsing job', max_length=255, null=True),
        ),
    ]
